import './colony.css';
import { ColonyScene } from './colony-scene.js';
import { ColonyState } from './colony-state.js';
import { Brain3D } from './brain-3d.js';
import { NeuralRuntime } from './neural-runtime.js';
import { configureAssetBase } from './data-loader.js';
import { populations } from './stimulus.js';
import { selectedCells } from './tape.js';

configureAssetBase(new URL('/',location.origin).href);
const $=id=>document.getElementById(id),state=new ColonyState(),cards=new Map();
let scene,brain,neural,pools={},selected='',signature='',light=false,stopped=false,lastFrame=0,lastCards=0,received=false,miniBase;
try{light=localStorage.getItem('flydex-theme')==='light';}catch{}
function applyTheme(){document.documentElement.dataset.theme=light?'light':'dark';$('theme').textContent=light?'Dark mode':'Light mode';scene?.setTheme(light);brain?.setTheme(light);if(brain?.neurons.length)makeMiniBase();}
$('theme').onclick=()=>{light=!light;applyTheme();try{localStorage.setItem('flydex-theme',light?'light':'dark');}catch{}};applyTheme();
function choose(address){if(!state.agents.has(address))return;const changed=selected!==address;selected=address;if(scene)scene.selected=address;if(changed)neural?.reset();
  const a=state.agents.get(address);$('network-title').textContent=a.token.symbol+' · neural network';$('selected-name').textContent=a.token.name;$('open-room').href='/?token='+encodeURIComponent(address);$('selected-caption').textContent=a.token.symbol+' · '+(a.token.pinned?'Our fly':a.token.name);
  for(const [key,card] of cards)card.button.setAttribute('aria-pressed',String(key===address));for(const b of state.agents.values())b.label?.setAttribute('aria-pressed',String(b.token.address===address));updateSelected();
}
function updateSelected(){const a=state.agents.get(selected);if(!a)return;$('selected-response').textContent=a.motion.active&&a.last?`${a.last.reaction.label} · ${a.last.reaction.mood} · ${a.last.population}`:a.token.marketStatus==='unavailable'?'No indexed market available':a.token.marketStatus==='discovering'?'Discovering token markets':'Resting · waiting for a new swap';}
try{scene=new ColonyScene($('garden'),$('fly-labels'),choose);scene.setTheme(light);$('garden-loading').hidden=true;}catch{$('garden-loading').textContent='This browser could not start the 3D garden. The live dashboard is still available.';}
$('overview').onclick=()=>scene?.overview();$('focus').onclick=()=>scene?.focus();
for(const button of document.querySelectorAll('[data-fullscreen]'))button.onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $(button.dataset.fullscreen).requestFullscreen();}catch{button.title='Full screen is unavailable in this browser';}};
$('reset-brain').onclick=()=>brain?.resetCamera();$('edges').onclick=()=>{if(brain){brain.showEdges=!brain.showEdges;$('edges').setAttribute('aria-pressed',String(brain.showEdges));}};
$('projection').onclick=()=>{if(brain){brain.projection=brain.projection==='brain'?'all':'brain';brain.layout();$('projection').textContent=brain.projection==='brain'?'Brain + nerve cord':'Brain only';}};
async function loadBrain(){try{brain=new Brain3D($('network'));brain.setTheme(light);const rows=await brain.load();const groups=populations(rows),matching=expression=>rows.flatMap((r,i)=>expression.test(r[1]||'')?[i]:[]);const sugar=matching(/sugar|Gr64|Gr5a|sweet/i),bitter=matching(/bitter|Gr66|Gr32/i),water=matching(/water|ppk28/i);pools={'Sugar / GRN attractant':sugar.length?sugar:groups.walk,'Sugar + PAM-like reward':[...(sugar.length?sugar:groups.walk),...matching(/^PAM/)],'Bitter / deterrent':bitter.length?bitter:groups.reverse,'Water / mild sugar':water.length?water:groups.walk,'Looming / LC4':groups.escapeInput};makeMiniBase();$('network-loading').hidden=true;neural=new NeuralRuntime(brain,$('neural-status'),()=>!document.hidden);}
  catch{$('network-loading').textContent='Neural network unavailable. Reload to retry.';$('neural-status').textContent='Live token tracking continues';}}
void loadBrain();
function makeMiniBase(){miniBase=document.createElement('canvas');miniBase.width=360;miniBase.height=120;const ctx=miniBase.getContext('2d'),rows=brain.neurons.filter(r=>r[6]&&r[6][2]>=9000&&r[6][2]<=58000);const xs=rows.map(r=>r[6][0]),zs=rows.map(r=>r[6][2]);let minX=Infinity,maxX=-Infinity,minZ=Infinity,maxZ=-Infinity;for(let i=0;i<xs.length;i++){minX=Math.min(minX,xs[i]);maxX=Math.max(maxX,xs[i]);minZ=Math.min(minZ,zs[i]);maxZ=Math.max(maxZ,zs[i]);}miniBase.bounds={minX,maxX,minZ,maxZ};for(let i=0;i<rows.length;i+=17){const p=rows[i][6],t=(p[0]-minX)/(maxX-minX);ctx.fillStyle=`hsla(${270-t*220},${light?45:65}%,${light?38:64}%,.48)`;ctx.fillRect(350-t*340,110-(p[2]-minZ)/(maxZ-minZ)*100,1.3,1.3);}}
function miniature(canvas,a){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,360,120);if(!miniBase){ctx.fillStyle=light?'#627080':'#919caa';ctx.font='16px Inter, sans-serif';ctx.fillText('Loading anatomy',10,65);return;}ctx.drawImage(miniBase,0,0);const decay=Math.max(0,1-(Date.now()-a.lastPulse)/6000);if(!a.last||!decay)return;const {minX,maxX,minZ,maxZ}=miniBase.bounds;ctx.fillStyle=a.last.side==='sell'?`rgba(255,80,98,${decay})`:`rgba(45,245,133,${decay})`;for(const index of selectedCells(pools[a.last.population]||[],a.last.tx)){const p=brain.neurons[index]?.[6];if(!p||p[2]<minZ||p[2]>maxZ)continue;ctx.beginPath();ctx.arc(350-(p[0]-minX)/(maxX-minX)*340,110-(p[2]-minZ)/(maxZ-minZ)*100,2.5,0,Math.PI*2);ctx.fill();}}
function rebuild(){cards.clear();$('token-grid').replaceChildren();for(const [address,a] of state.agents){const button=document.createElement('button');button.className='token-card';button.setAttribute('aria-label','Inspect '+a.token.name);button.onclick=()=>choose(address);
    const top=document.createElement('div');top.className='token-card-top';const avatar=document.createElement('span');avatar.className='avatar';avatar.textContent=a.token.symbol.slice(0,2);if(a.token.image){const img=document.createElement('img');img.src=a.token.image;img.alt='';img.loading='lazy';img.referrerPolicy='no-referrer';img.onerror=()=>{img.remove();};avatar.replaceChildren(img);}
    const titles=document.createElement('span');titles.className='token-titles';const strong=document.createElement('strong');strong.textContent=a.token.symbol;const small=document.createElement('small');small.textContent=a.token.pinned?'Our fly · '+a.token.name:a.token.name;titles.append(strong,small);const number=document.createElement('span');number.className='fly-number';number.textContent=String(cards.size+1).padStart(2,'0');top.append(avatar,titles,number);
    const canvas=document.createElement('canvas');canvas.className='mini-brain';canvas.width=360;canvas.height=120;canvas.setAttribute('aria-label','Direct stimulation map for '+a.token.symbol);const status=document.createElement('div');status.className='card-status';const response=document.createElement('div');response.className='card-response';button.append(top,canvas,status,response);$('token-grid').append(button);cards.set(address,{button,canvas,status,response});
  }scene?.setAgents([...state.agents.values()]);choose(state.agents.has(selected)?selected:state.agents.keys().next().value);filter();}
function filter(){const term=$('filter').value.trim().toLowerCase();let count=0;for(const [address,c] of cards){const t=state.agents.get(address).token;c.button.hidden=![t.name,t.symbol,address].some(s=>s.toLowerCase().includes(term));if(!c.button.hidden)count++;}$('empty-dashboard').hidden=count>0;$('empty-dashboard').textContent=state.agents.size?'No matching tokens':'Loading the latest migrations…';}
$('filter').oninput=filter;
function updateCards(){let active=0,observed=0;for(const [address,c] of cards){const a=state.agents.get(address);if(!a)continue;observed+=a.observed;if(a.motion.active)active++;c.status.textContent=(a.token.marketStatus==='indexed'?'Watching':a.token.marketStatus==='discovering'?'Discovering':'No indexed pool')+' · '+a.observed+' swaps';c.response.textContent=a.motion.active&&a.last?a.last.reaction.label+' · '+a.last.reaction.mood:'Resting';c.button.dataset.side=a.motion.active?a.last?.side||'':'';if(a.label)a.label.dataset.side=c.button.dataset.side;if(!c.button.hidden)miniature(c.canvas,a);}$('active-count').textContent=active;$('swap-count').textContent=observed;updateSelected();}
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2});
function renderFeed(){const rows=state.events.slice(-80).reverse();$('empty-events').hidden=rows.length>0;$('colony-events').replaceChildren(...rows.map(e=>{const tr=document.createElement('tr');for(const [i,text] of [new Date(e.ts).toLocaleTimeString('en-GB'),state.agents.get(e.token)?.token.symbol||'Token',e.side,money.format(e.usd),e.population,e.reaction.label].entries()){const td=document.createElement('td');if(i===1){const a=document.createElement('a');a.href='/?token='+encodeURIComponent(e.token);a.textContent=text;td.append(a);}else td.textContent=text;if(i===2)td.className=e.side;tr.append(td);}return tr;}));}
async function poll(){if(stopped)return;try{const response=await fetch('/api/colony',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(!response.ok)throw Error('Market connection delayed');const data=await response.json();if(stopped)return;const pulses=state.accept(data);const next=[...state.agents.keys()].join();if(signature!==next){signature=next;rebuild();}else if(selected)choose(selected);
    for(const {agent,event} of pulses)if(agent.token.address===selected){const cells=selectedCells(pools[event.population]||[],event.tx);brain?.stimulate(cells,event.side);neural?.pulse(cells,event.gain);}
    const indexed=data.tokens.filter(t=>t.marketStatus==='indexed').length;$('indexed-count').textContent=indexed;$('fly-count').textContent=state.agents.size+' / 50';$('dashboard-count').textContent=state.agents.size?String(state.agents.size):'';
    $('connection').textContent=data.status==='connected'?'Live · Robinhood Chain':data.tokens.some(t=>t.marketStatus==='discovering')?'Discovering markets':data.error||'Connecting to markets';$('coverage').textContent=indexed+' indexed tokens · '+(data.watcher?.poolCount||0)+' pools'+(data.watcher?.catchupError?' · recovery scan delayed':' · two-block confirmation');
    if(pulses.length||!received)renderFeed();received=true;
  }catch{$('connection').textContent='Connection interrupted · retrying';$('coverage').textContent='Activity may be delayed';}finally{if(!stopped)setTimeout(poll,document.hidden?5000:1500);}}
void poll();
function frame(now){if(stopped)return;requestAnimationFrame(frame);const dt=Math.min(.05,(now-(lastFrame||now))/1000);lastFrame=now;if(document.hidden)return;if(scene)scene.render(dt,now);else for(const a of state.agents.values())a.motion.advance(dt);if(now-lastCards>250){lastCards=now;updateCards();}}
requestAnimationFrame(frame);
window.addEventListener('pagehide',()=>{stopped=true;neural?.worker.terminate();if(neural)clearTimeout(neural.timer);brain?.dispose();scene?.dispose();});
window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
